# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Cleanup npm registry (v1.1a)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  version: '1.1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@leanup'
      - name: Set up Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.x
      - name: Unpublish deprecated packages
        shell: bash
        run: bash ./unpublish-${{ env.version }}-a.sh
        working-directory: ./scripts/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
